repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args: ['--unsafe']

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args:
          - "--extend-ignore=E203,E501"
          - "--max-line-length=88"

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0
  #   hooks:
  #     - id: mypy
  #       args: [--install-types, --non-interactive]
  #       additional_dependencies: [types-requests]

  - repo: local
    hooks:
      - id: pytest-with-deps
        name: Run pytest with dependencies
        entry: sh -c "pip install pytest && pip install -r requirements.txt && pytest tests/"
        language: python
        types: [python]
        pass_filenames: false
        require_serial: true
