services:
  parser:
    build: .
    # depends_on:
    #   - data-loader
    env_file:
      - .env
    volumes:
      - ./${DATA_STORAGE_DIR}:/app/${DATA_STORAGE_DIR}               # only if you store data in directory, else delete volumes
    command: [ "python", "main.py" ]
