services:
  parser:
    build: .
    # depends_on:
    #   - data-loader
    env_file:
      - .env
    volumes:
      - ./data:/app/data               # only if you store data in directory, else delete volumes
    command: [ "python", "main.py" ]
